# Generated by Django 4.0 on 2025-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, default=None, help_text='The user is banned until this date and time.', null=True),
        ),
    ]
