# Generated by Django 4.0 on 2025-11-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ban_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, default=0, help_text='The user is banned until this date and time.', null=True),
        ),
    ]
