# Generated by Django 4.0 on 2025-12-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_ban_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_allowed',
            field=models.IntegerField(default=3),
        ),
    ]
