# Generated by Django 4.2.28 on 2026-02-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_max_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, default=None, help_text='The user is banned until this date and time.', null=True),
        ),
    ]
