# Generated by Django 4.2.28 on 2026-03-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_img_alter_user_ban_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('student', 'student'), ('teacher', 'teacher')], default='student', max_length=10),
        ),
    ]
