# Generated by Django 4.2.28 on 2026-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('librarian', 'librarian'), ('student', 'student'), ('teacher', 'teacher')], default='student', max_length=10),
        ),
    ]
