# Generated by Django 4.0 on 2025-10-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='c_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-17 10:20:25.654487'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitob',
            name='u_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
