# Generated by Django 4.0 on 2025-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_kitob_c_at_kitob_u_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('u_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('iccn', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='kitob',
            name='is_available',
            field=models.BooleanField(),
        ),
    ]
