# Generated by Django 4.0 on 2025-11-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_journals_alter_kitob_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='is_frequent',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitob',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
