# Generated by Django 4.0 on 2025-12-15 10:55

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_kitob_is_frequent_alter_kitob_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='u_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kitob',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitob',
            name='read_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='kitob',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
