# Generated by Django 4.2.28 on 2026-02-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_category_c_at_category_u_at_category_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ebook_images/'),
        ),
        migrations.AddField(
            model_name='journals',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='journals_images/'),
        ),
        migrations.AddField(
            model_name='kitob',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='journals',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journals',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
