# Generated by Django 4.2.28 on 2026-03-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_author_remove_kitob_reader_kitob_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
