# Generated by Django 4.2.29 on 2026-03-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_reservation_reserved_from_reservation_reserved_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('given', 'Given'), ('returned', 'Returned'), ('not_returned', 'Not Returned')], default='pending', max_length=20),
        ),
    ]
