# Generated by Django 4.2.29 on 2026-03-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_reservation_approved_at_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
